name = "Hikari"
uuid = "afc56b53-c9a9-482a-a956-d1d800e05558"
version = "0.1.0"
authors = ["Anton Smirnov <tonysmn97@gmail.com>", "Simon Danisch <sdanisch@proton.me>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomNumbers = "e6cf234a-135c-5ec9-84dd-332b85af5143"
Raycore = "afc56b53-c9a9-482a-a956-d1d800e05559"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"

[compat]
Adapt = "4.4.0"
FileIO = "1.16"
GPUArraysCore = "0.2.0"
GeometryBasics = "0.4, 0.5"
ImageCore = "0.10"
ImageIO = "0.6"
ProgressMeter = "1.10"
RandomNumbers = "1.6.0"
StaticArrays = "1.9.7"
StructArrays = "0.6.18"
Zlib_jll = "1.3.1"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JET"]
